version: "3"

services:
 
 mongo:
  image: mongo
  container_name: mongo
  ports:
   - 27017:27017
  volumes:
   - mongodata:/data/db
 
 
 
 rabbitmq:
  image: rabbitmq:management
  container_name: mq
  ports:
   - 3005:5672
   - 3004:15672
  volumes:
   - rabbitmqdata:/var/lib/rabbitmq
  hostname: rabbitmq

volumes:
 rabbitmqdata:
 mongodata: