version: "3"

services:
 
 mongo:
  image: mongo
  container_name: mongo
  ports:
   - 27017:27017
  volumes:
   - mongodata:/data/db
 
 
 
 rabbitmq:
  image: rabbitmq:management
  container_name: mq
  ports:
   - 5672:5672
   - 15672:15672
  volumes:
   - rabbitmqdata:/var/lib/rabbitmq
  hostname: rabbitmq

invetario:
 build: ./inv
 container_name: inventario
 restart: always
 ports:
  - 8081:80

catalogo
 build: ./cat
 container_name: catalogo
 ports:
  - 8080:80


volumes:
 rabbitmqdata:
 mongodata: